project_name: notify_slack
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/notify_slack/main.go
    binary: notify_slack
    ldflags:
      - -s -w
      - -X github.com/catatsuy/notify_slack/internal/cli.Version=v{{.Version}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
release:
  prerelease: auto
